name: .NET

on:
  schedule:
  #Run each day at 22:15
    - cron: '15 22 * * *'
  pull_request:
    paths:
      - 'ui_tests/**'

jobs:
  tests_unitTests:
    name: Unit and UI tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./ui_tests/PlaywrightAutomation.sln

    - name: Override config parameters
      shell: pwsh
      run: |
        Try
          {
            $configPath = './ui_tests/PlaywrightAutomation/appsettings.json'
            $jsonConfig = Get-Content $configPath | Out-String | ConvertFrom-Json
            $jsonConfig.Browser_Headless = 'true'
            $jsonConfig | ConvertTo-Json -depth 100 | Out-File $configPath
          }
          Catch
          {
            throw "$_.Exception.ToString()"
          }

    - name: Build
      run: dotnet build ./ui_tests/PlaywrightAutomation.sln --no-restore
      
    - name: Run Playwright installation
      shell: pwsh
      run: pwsh -Command "./ui_tests/PlaywrightAutomation/bin/Debug/net6.0/playwright.ps1 install"
      
    # Jobs to run on each PR
    - name: Unit tests
      id: unitTests
      if: github.event_name == 'pull_request'
      run: dotnet test ./ui_tests/PlaywrightAutomation.sln --filter "TestCategory=OnBuild" --no-build --verbosity normal
      
    - name: UI tests
      if: github.event_name == 'pull_request'
      run: dotnet test ./ui_tests/PlaywrightAutomation.sln --filter "TestCategory=Smoke&TestCategory!=NotRun"
    
    # Jobs to run on Schedule
    - name: UI tests on Schedule
      if: github.event_name == 'schedule'
      run: dotnet test ./ui_tests/PlaywrightAutomation.sln --filter "TestCategory!=OnBuild&TestCategory!=NotRun"
      
    # Slack message of Unit tests fail  
    - name: Slack Notification for Unit tests
      if: ${{ steps.unitTests.outcome != 'success' && failure() }} 
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: Tests execution report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ts_website_automation
        SLACK_ICON_EMOJI: ':warning:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        SLACK_TITLE: .Net Unit tests
        MSG_MINIMAL: true
        SLACK_FOOTER: TS website
    
    # Steps to report UI tests execution status
    # Prepare Allure history and publish to GitHub pages
    - name: Get Allure history
      uses: actions/checkout@v3
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }} 
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Compile Allure report
      uses: simple-elf/allure-report-action@master
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }} 
      with:
        allure_results: ui_tests/PlaywrightAutomation/bin/Debug/net6.0/allure-results
        allure_history: ui_tests/PlaywrightAutomation/bin/Debug/net6.0/allure-history
        keep_reports: 30
          
    - name: Deploy Allure Report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }} 
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: ui_tests/PlaywrightAutomation/bin/Debug/net6.0/allure-history
        
    - name: Add Allure report link to Annotations section
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }}
      run: |
        text="https://tech-stack-dev.github.io/ts-website-automation/${{ github.run_number }}"
        echo "::warning ::$text"
         
    - name: Preparing Slack emoji
      uses: haya14busa/action-cond@v1
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }} 
      id: slack_icon_emoji
      with:
        cond: ${{ job.status == 'failure' }}
        if_true: ':finnadie:'
        if_false: ':aw_yeah:'
          
    - name: Slack Notification for UI tests
      if: ${{ steps.unitTests.outcome == 'success' && ((github.event_name == 'schedule') || (github.event_name == 'pull_request' && failure())) }} 
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: Tests execution report to QA Service channel
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ts_website_automation
        SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: https://tech-stack-dev.github.io/ts-website-automation/${{ github.run_number }}
        SLACK_TITLE: .Net UI tests
        MSG_MINIMAL: true
        SLACK_FOOTER: TS website
        
    - name: Slack Notification for UI tests to Product channel
      if: ${{ (steps.unitTests.outcome == 'success') && (github.event_name == 'schedule') }} 
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: Tests execution report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ts_website
        SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: https://tech-stack-dev.github.io/ts-website-automation/${{ github.run_number }}
        SLACK_TITLE: .Net UI tests
        MSG_MINIMAL: true
        SLACK_FOOTER: TS website
        