name: .NET

on:
  pull_request:
    paths:
      - "performance_tests/**"
      - "ui_tests_playwright/**"
    # Use paths-ignore instead of path after fix of https://github.com/actions/runner/issues/2324
    # paths-ignore:
    #   - "ui_tests/**"

jobs:
  tests_unitTests:
    name: .Net unit tests
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests execution required"'
