name: .NET

on:
  pull_request:
    paths:
      - "performance_tests/**"
      - "ui_tests_playwright/**"
        
jobs:
  tests_unitTests:
    name: .Net unit tests
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests execution required"'
