name: Playwright UI E2E
            
on:
  pull_request:
    paths:
      - "performance_tests/**"
      - "ui_tests/**"

jobs:
  tests_e2e:
    name: Playwright end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests execution required"'
