name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: pre-commit/action@v3.0.0
    - uses: npm ci
    - uses: npm run lint