name: Upload selectors for plugin

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  upload_selectors:
    name: Check changes and upload selectors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changes in the identifiers folder
        id: changed-ids
        uses: tj-actions/changed-files@v34
        with:
          files: ui_tests_playwright/automation/identifiers/**

      - name: Run upload if identifiers were changed
        if: steps.changed-ids.outputs.any_changed == 'true'
        run: |
          echo Some identifiers were changed;
          bash ./scripts/selectors-upload.sh

      - name: Prevent from running if identifiers weren't changed
        if: steps.changed-ids.outputs.any_changed == 'false'
        run: echo Identifiers were not changed