name: Upload selectors for plugin

on:
  pull_request:
    branches: [main]
    paths: 
      - 'ui_tests_playwright/automation/identifiers/**'
    types: [closed]

jobs:
  upload_selectors:
    if: github.event.pull_request.merged == true
    name: Check changes and upload selectors
    runs-on: ubuntu-latest
    steps:
      - name: Run upload if identifiers were changed
        run: |
          echo Some identifiers were changed;
          bash ./scripts/selectors-upload.sh
